openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS04 - Change Request enrollment / Rettifica iscrizioni
  x-summary: Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  version: 1.0.0
  description: |
        Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
security: [{}]
paths:
  '/accademic-enrollment-change-request':
    post:
      summary: (OK) Correction of student registration / Rettifica iscrizione studente
      operationId: rectification-student-enrollment
      tags:
        - accademic enrollment change request
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Registration correction request sent successfully / Richiesta rettifica iscrizione inviata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example res 1:
                  value:
                    file_status: aquired
                    file_code: 6d183bc572f6b200015a4167
                    message: Richiesta rettifica iscrizione acquisita
        '404':
          description: Student not found / Studente non trovato
        '500':
          description: Internal server error / Errore interno del server 
      description: Allows  to create a request to correct data relating to a student's registration / Permette di creare una richiesta di rettifica dei dati relativi alle iscrizioni di una studentessa o uno studente.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  reason: Modifica iscrizione xxx
                  attributes:
                      - attribute_name: institute_Name
                        current: Università degli studi di Milano
                        suggested: Università degli studi di Roma 'La Sapienza'
                      - attribute_name: course_type
                        current: Laurea
                        suggested: Corso di Laurea
                      - attribute_name: enrollment_year
                        current: 2021/2022
                        suggested: 2022/2023
                      - attribute_name: course_year
                        current: 2° anno
                        suggested: 3° anno
                  request: Testo con la richiesta di rettifica
                  note: Note aperte studentessa o studente
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
    parameters: []
  '/accademic-enrollment-change-request-status':
  
    post:
      summary: (OK) Student enrolment correction detail / Dettaglio rettifica iscrizione studentessa o studente
      tags:
        - accademic enrollment change request status
      parameters: []
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request executed successfully / Richiesta eseguita con successo (annulamento)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enrollments_change_request'
              examples:
                Example 1:
                  value: 
                    enrollment_change_request:
                      - file_status: approved
                        file_code: 6d183bc572f6b200015a4167
                        message: testo messaggio
                      - file_status: rejected
                        file_code: 6d183b54654127dfhh15a4167
                        message: testo messaggio  
        '404':
          description: Registration correction not found / Rettifica iscrizione non trovata
        '500':
          description: Internal server error / Errore interno del server 
      operationId: detail-enrollment-rectification
      description: Allows you to retrieve the status of a registration adjustment request via its identifier / Permette di recuperare lo stato di una richiesta di rettifica iscrizione tramite il suo identificativo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'      
  '/accademic-enrollment-change-request-cancellation':
    post:
      summary: Cancellation of change request / Richiesta di annullamento rettifica
      tags:
        - accademic enrollment change request cancellation
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request for cancellation of rectification completed successfully / Richiesta annullamento rettifica eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example 1:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: messaggio di testo
        '500':
          description: Internal server error / Errore interno del server 
      operationId: rectification-cancellation
      description: Rectification cancellation request / Effettua la richiesta di annullamento rettifica 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'            
    parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    change_request:
      type: object
      additionalProperties: false      
      x-examples:
        Example 1:
          tax_code: RSSMRA80A01F205D
          reason: Modifica iscrizione xxx
          attributes:
              - attribute_name: institute_name
                current: Università degli studi di Milano
                suggested: Università degli studi di Roma 'La Sapienza'
              - attribute_name: degree_course_type
                current: Laurea
                suggested: Corso di Laurea
              - attribute_name: registratio_year
                current: 2021/2022
                suggested: 2022/2023
              - attribute_name: degree_cours_Year
                current: 2° anno
                suggested: 3° anno
          request: Testo con la richiesta di rettifica
          note: Note aperte dello studente/ex studente
      x-stoplight:
        id: b40e2be27c423
      description: Request creation rectification of a student's enrollment / Richiesta creazione rettifica iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
          readOnly: true
        reason:
          type: string
          description: Modification description / Descrizione modifica
          example: Modifica iscrizione xxx
          minLength: 1
          maxLength: 256
          readOnly: true  
        attributes:
          $ref: '#/components/schemas/attributes'
        request:
          type: string
          description: Text with request for rectification / Testo con la richiesta di rettifica
          readOnly: true
          minLength: 1
          maxLength: 5000
        note:
          type: string
          description: Open notes from student / Note aperte studentessa o studente
          readOnly: true
          minLength: 1
          maxLength: 5000
      required:
        - tax_code
    enrollments_change_request:
      type: object
      additionalProperties: false
      x-examples:
        Example 1:
          enrollment_change_request:
            - file_status: approved
              file_code: 6d183bc572f6b200015a4167
              message: testo messaggio
            - file_status: rejected
              file_code: 6d183b54654127dfhh15a4167
              message: testo messaggio  
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        enrollment_change_request:
          type: array
          minItems: 0
          maxItems: 256
          description: List of enrollments for student / Elenco iscrizioni di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/change_request_detail'
    change_request_detail:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          file_status: accepted
          file_code: 908d3e72b51a6f0034e2a11c
          message: accettata
      description: Status of an enrollment rectification for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Attribute name to be changed when rectification enrollment / Nome attributo da variare in fase di rettifica iscrizione
          readOnly: true
          minLength: 1
          maxLength: 256
          enum:
            - approved 
            - rejected
            - aquired
        file_code:
          type: string
          description: Current value of the field to be varied / Valore corrente del campo da variare
          readOnly: true
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: New value to be replaced during rectification / Nuovo valore da sostituire in fase di rettifica
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
    attributes:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of attributes to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/attribute'
    attribute:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          attribute_name: degree_course_year
          current: 5
          suggested: 4
      description: Status of an enrollment rectification for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          description: Attribute name to be changed when rectification enrollment / Nome attributo da variare in fase di rettifica iscrizione
          readOnly: true
          minLength: 1
          maxLength: 256   
        current:
          type: string
          description: Current value to be rectified / Valore corrente da rettificare
          readOnly: true
          minLength: 1
          maxLength: 256    
        suggested:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - current
        - suggested
    enrollment_change_request:
      type: object
      additionalProperties: false      
      x-examples:
        Example 1:
          tax_code: RSSMRA80A01F205D
          person_id: 12345678A
          institute_code: AA
      x-stoplight:
        id: b40e2be27c423
      description: Request enrollment of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
          readOnly: false
        person_id:
          type: string
          description: National unique identifier / Identificativo unico nazionale
          example: 12345678A
          minLength: 9
          maxLength: 9
          readOnly: false  
        file_code:
          type: string
          description: change request enrollment code/ Codice Rettifica iscrizioni
          example: 6d183bc572f6b200015a4167
          minLength: 1
          maxLength: 64
          readOnly: false  
      required:
        - tax_code     
        - file_code
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO  
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: accademic enrollment change request
  - name: accademic enrollment change request status
  - name: accademic enrollment change request cancellation
  - name: health-check
  